### ISSUE TITLE
Pagination pre vyhľadávanie

### ISSUE THREAD

**Issue by Voltrifrodec** [Voltrifrodec/bazarik-be#21]
- Odkaz na pôvodnú issue: #10 
- Odkaz pre issue na FE: https://github.com/Voltrifrodec/bazarik-fe/issues/111

## Task
- [x] úprava `AdvertPageRepository`: pridať `findAllByQuery`
- [x] vytvorenie `getPaginatedAdvertsByQuery()` pre `AdvertService`
- [x] úprava `@GetMapping`
- [x] testovanie na BE
- [x] testovanie na FE

**Comment by VOJAKIS** [comment]
Server vráti chybu, ak nezadáme page size (=page size musí byť väčšia ako 0)

Riešenie:
- [x] Nastaviť počiatočnú hodnotu do PageRequestDto .page=0, .size=10
